### ISSUE TITLE
could you update it for 4.1 version?

### ISSUE THREAD

**Issue by lxregistry** [whiteoctober/WhiteOctoberTCPDFBundle#46]
Service "white_october.tcpdf" not found: even though it exists in the app's container, the container inside

**Comment by sampart** [comment]
Hi @lxregistry, thanks for your feedback.

Have you added the bundle to `config/bundles.php`?  There's not yet a Symfony Flex recipe for this project, so this won't happen automatically.

**Comment by finkbg** [comment]
It works in 4.1. Just make sure you make the service public in your config/services.yaml like that:

```
services:
   ...
    white_october.tcpdf.public:
        alias: white_october.tcpdf
        public: true
```
